### ISSUE TITLE
guide to install this code to HA

### ISSUE THREAD

**Issue by CuongHome** [MassiPi/ld2450_ble#1]
Hi could someone point to a guide of how to install this code to HA, been searching for awhile and couldn't find anything.

**Comment by MassiPi** [comment]
download the repository (code -> download zip)
extract the folder you'll find in the zip (ld2450_ble-main) in your custom_components folder
(i'd rename the folder from ld2450_ble-main to ld2450_ble)
restart ha
should be ok. If there is a 2450 around, HA should discover it and ask you for configuration

**Comment by MassiPi** [comment]
i can't see the screenshot :)

**Comment by eingabe** [comment]
![2450_1](https://github.com/user-attachments/assets/a2e84a18-2bba-49ed-b4aa-622446177da3)
![2450_2](https://github.com/user-attachments/assets/5b7c4a23-4c01-485f-a3d2-cba93cd4dddc)
I download the zip, and upload it to the folder. I found the integration but i get on error. Can you help?

**Comment by MassiPi** [comment]
what are system registers saying?

**Comment by eingabe** [comment]
What do you meen? Any example?

**Comment by MassiPi** [comment]
home assistant logs

**Comment by eingabe** [comment]
Thx for help.
i can not install the package, i get this error all the time. i hope you can help

Logger: homeassistant.util.package
Quelle: util/package.py:123
Erstmals aufgetreten: 08:03:53 (3 Vorkommnisse)
Zuletzt protokolliert: 08:03:55

Unable to install package bluetooth-data-tools==1.19.0: ERROR: Cannot install bluetooth-data-tools==1.19.0 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by MassiPi** [comment]
oh nice, i'm not using the sensor at the moment, probably it's something sourcing from recent HA versions..
can you try editing the manifest.json file from this:
```
"requirements": ["bluetooth-data-tools==1.19.0"]
```

to something like this?
```
"requirements": ["bluetooth-data-tools>=1.19.0"]
```

let's see what happens with newer versions :)

**Comment by eingabe** [comment]
now, i get no system error BUT Popup error:
[%key:common::config_flow::abort::no_devices_found%]

but my BT device is online

**Comment by MassiPi** [comment]
ok, i need to put back the sensor in action and see :)
let me go back home this evening..

**Comment by MassiPi** [comment]
yes, i can confirm the issue.
something broke also for original ld2410_ble integration that this integration is based on
let's see..
https://github.com/930913/ld2410-ble/issues/8

**Comment by eingabe** [comment]
So there is no way to connect the sensor directly, right?
